import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center bg-custom-black`}
      >
          {/* Navbar */}
          <main className="flex flex-col gap-10 py-10 min-h-screen max-w-[60rem] overflow-hidden font-satoshi text-[0.92rem] leading-relaxed">
            {children}
          </main>
      </body>
    </html>
  );
}
